// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3c41d149c8dc
import { RecordDetail } from "@/components/dashboard/record-detail";
import decisionResource from "@/resources/decision.resource";

export default async function DecisionDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={decisionResource} id={(await params).id} />;
}
// generated:end
