import {
  BellIcon,
  BookIcon,
  WalletIcon,
  BoxIcon,
  BriefcaseIcon,
  Building2Icon,
  CalendarIcon,
  ChartBarIcon,
  ClipboardListIcon,
  CreditCardIcon,
  DatabaseIcon,
  DollarSignIcon,
  FileTextIcon,
  FolderIcon,
  GlobeIcon,
  HeartIcon,
  ImageIcon,
  LayersIcon,
  MailIcon,
  MapPinIcon,
  MessageSquareIcon,
  PackageIcon,
  PhoneIcon,
  ReceiptIcon,
  SettingsIcon,
  ShieldAlertIcon,
  RadioIcon,
  ShieldIcon,
  ShoppingCartIcon,
  StarIcon,
  TagIcon,
  TicketIcon,
  TruckIcon,
  UserIcon,
  UsersIcon,
  WrenchIcon,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons a resource descriptor can name (`icon: "users"`). Imported by name so unused
 * ones are tree-shaken; add the lucide icons your app needs.
 */
export const RESOURCE_ICONS: Record<string, LucideIcon> = {
  bell: BellIcon,
  book: BookIcon,
  wallet: WalletIcon,
  box: BoxIcon,
  briefcase: BriefcaseIcon,
  building: Building2Icon,
  calendar: CalendarIcon,
  chart: ChartBarIcon,
  clipboard: ClipboardListIcon,
  "credit-card": CreditCardIcon,
  database: DatabaseIcon,
  dollar: DollarSignIcon,
  file: FileTextIcon,
  folder: FolderIcon,
  globe: GlobeIcon,
  heart: HeartIcon,
  image: ImageIcon,
  layers: LayersIcon,
  mail: MailIcon,
  "map-pin": MapPinIcon,
  message: MessageSquareIcon,
  package: PackageIcon,
  phone: PhoneIcon,
  receipt: ReceiptIcon,
  settings: SettingsIcon,
  radio: RadioIcon,
  shield: ShieldIcon,
  "shield-alert": ShieldAlertIcon,
  cart: ShoppingCartIcon,
  star: StarIcon,
  tag: TagIcon,
  ticket: TicketIcon,
  truck: TruckIcon,
  user: UserIcon,
  users: UsersIcon,
  wrench: WrenchIcon,
};

/** The icon for a resource, falling back to a generic document icon. */
export function resourceIcon(name: string | undefined): LucideIcon {
  return (name && RESOURCE_ICONS[name]) || FileTextIcon;
}
