// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f03824c4656e
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import componentResource from "@/resources/component.resource";

export const metadata = { title: componentResource.pluralLabel };

export default async function ComponentListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={componentResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: componentResource.pluralLabel }]}
      />
      <ResourceStats resource={componentResource} />
      <ResourceChart resource={componentResource} />
      <ResourceTable resource={componentResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
