// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=96d60b82e892
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import securityEventResource from "@/resources/security-event.resource";

export default function NewSecurityEventPage() {
  return <ResourceFormPage resource={securityEventResource} />;
}
// generated:end
