// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=d2ce85caaa74
import { FormSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton actions={0} />
      <FormSkeleton fields={3} />
    </>
  );
}
// generated:end
