// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=4f6938cbc463
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import dependencyResource from "@/resources/dependency.resource";

export default async function EditDependencyPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={dependencyResource} id={(await params).id} />;
}
// generated:end
