// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=6db35e575aef
import { ResourceListSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return <ResourceListSkeleton columns={4} />;
}
// generated:end
