// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=15fbdac2e56b
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import dependencyResource from "@/resources/dependency.resource";

export const metadata = { title: dependencyResource.pluralLabel };

export default async function DependencyListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={dependencyResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: dependencyResource.pluralLabel }]}
      />
      <ResourceStats resource={dependencyResource} />
      <ResourceChart resource={dependencyResource} />
      <ResourceTable resource={dependencyResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
