// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=a78c2e8d317f
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import decisionResource from "@/resources/decision.resource";

export default async function EditDecisionPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={decisionResource} id={(await params).id} />;
}
// generated:end
