// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3318bc8a63ad
import { createResourceClient } from "@flaredev/core/client";
import type componentResource from "./component.resource";

export const componentClient = createResourceClient<typeof componentResource>("/api/components");

export type Component = typeof componentResource.$types.record;
export type ComponentCreate = typeof componentResource.$types.create;
export type ComponentUpdate = typeof componentResource.$types.update;
// generated:end
