// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=f6b60b9b9c6a
import { createValidators } from "@flaredev/core";
import componentResource from "./component.resource";

export const componentValidators = createValidators(componentResource);
// generated:end

import { z } from "zod";

componentValidators.create = (componentValidators.create as any).extend({
  name: z.string().regex(/^[a-z0-9-]+$/, "Name must be lowercase alphanumeric and dashes"),
}) as any;
componentValidators.update = (componentValidators.update as any).extend({
  name: z.string().regex(/^[a-z0-9-]+$/, "Name must be lowercase alphanumeric and dashes").optional(),
}) as any;
