// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=32188df29374
import { createResourceClient } from "@flaredev/core/client";
import type decisionResource from "./decision.resource";

export const decisionClient = createResourceClient<typeof decisionResource>("/api/decisions");

export type Decision = typeof decisionResource.$types.record;
export type DecisionCreate = typeof decisionResource.$types.create;
export type DecisionUpdate = typeof decisionResource.$types.update;
// generated:end
