// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3aa0df263d6b
import { createValidators } from "@flaredev/core";
import decisionResource from "./decision.resource";

export const decisionValidators = createValidators(decisionResource);
// generated:end
