// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=63b094547dcc
import { createValidators } from "@flaredev/core";
import dependencyResource from "./dependency.resource";

export const dependencyValidators = createValidators(dependencyResource);
// generated:end
