// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=cbf67c683860
import { createResourceClient } from "@flaredev/core/client";
import type dependencyResource from "./dependency.resource";

export const dependencyClient = createResourceClient<typeof dependencyResource>("/api/dependencies");

export type Dependency = typeof dependencyResource.$types.record;
export type DependencyCreate = typeof dependencyResource.$types.create;
export type DependencyUpdate = typeof dependencyResource.$types.update;
// generated:end
