// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=0d53db50fab9
import { createValidators } from "@flaredev/core";
import securityEventResource from "./security-event.resource";

export const securityEventValidators = createValidators(securityEventResource);
// generated:end
