// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=c57d60b88318
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import decisionResource from "@/resources/decision.resource";

export default function NewDecisionPage() {
  return <ResourceFormPage resource={decisionResource} />;
}
// generated:end
