// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=2407548298e6
import { RecordDetail } from "@/components/dashboard/record-detail";
import dependencyResource from "@/resources/dependency.resource";

export default async function DependencyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={dependencyResource} id={(await params).id} />;
}
// generated:end
