// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=55b7c9af3605
import { DetailSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton />
      <DetailSkeleton rows={8} />
    </>
  );
}
// generated:end
