// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=0472ece32b44
import { RecordDetail } from "@/components/dashboard/record-detail";
import securityEventResource from "@/resources/security-event.resource";

export default async function SecurityEventDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={securityEventResource} id={(await params).id} />;
}
// generated:end
