// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3e928317fd73
import { createResourceStore, prismaRows, crossOrigin, drain, failureResponse, problem, readJson, respond, type RouteContext } from "@/lib/resource";
import { prisma } from "@/lib/db";
import { authorize, currentUser, policyFor } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import securityEventResource from "@/resources/security-event.resource";

const store = createResourceStore({
  resource: securityEventResource,
  rows: prismaRows(prisma.securityEvent, prisma),
  currentUser,
  // The role half of the policy is checked by authorize() below; the `own` half
  // restricts which rows exist for this user, which only the store can do.
  policy: policyFor("SecurityEvent"),
  onChange: revalidateResource,
});

/** GET /api/security-events/[id] — read one security event. */
export async function GET(request: Request, context: RouteContext): Promise<Response> {
  const { id } = await context.params;
  const denied = await authorize({ request, resource: securityEventResource, action: "read", id });
  if (denied) return denied;

  return respond(await store.get(id));
}

/** PATCH /api/security-events/[id] — change some fields of one security event. */
export async function PATCH(request: Request, context: RouteContext): Promise<Response> {
  try {
    const { id } = await context.params;
    const denied = await authorize({ request, resource: securityEventResource, action: "update", id });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const read = await readJson(request);
    if ("response" in read) return read.response;

    return respond(await store.update(id, read.body));
  } finally {
    await drain(request);
  }
}

/** PUT /api/security-events/[id] — replace one security event entirely. */
export async function PUT(request: Request, context: RouteContext): Promise<Response> {
  try {
    const { id } = await context.params;
    const denied = await authorize({ request, resource: securityEventResource, action: "update", id });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const read = await readJson(request);
    if ("response" in read) return read.response;

    return respond(await store.replace(id, read.body));
  } finally {
    await drain(request);
  }
}

/** DELETE /api/security-events/[id] — remove one security event. */
export async function DELETE(request: Request, context: RouteContext): Promise<Response> {
  try {
    const { id } = await context.params;
    const denied = await authorize({ request, resource: securityEventResource, action: "delete", id });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const result = await store.delete(id);
    return result.ok ? new Response(null, { status: 204 }) : failureResponse(result);
  } finally {
    await drain(request);
  }
}
// generated:end
