// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=1f758d80830a
import { FormSkeleton, PageHeaderSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return (
    <>
      <PageHeaderSkeleton actions={0} />
      <FormSkeleton fields={4} />
    </>
  );
}
// generated:end
