// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=8f8af88e8a23
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import componentResource from "@/resources/component.resource";

export default function NewComponentPage() {
  return <ResourceFormPage resource={componentResource} />;
}
// generated:end
