// Generated by `flare gen resource Dependency`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=314b1511377e
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import dependencyResource from "@/resources/dependency.resource";

export default function NewDependencyPage() {
  return <ResourceFormPage resource={dependencyResource} />;
}
// generated:end
