// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=cb1e46f207c6
import { RecordDetail } from "@/components/dashboard/record-detail";
import componentResource from "@/resources/component.resource";

export default async function ComponentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  return <RecordDetail resource={componentResource} id={(await params).id} />;
}
// generated:end
