// Generated by `flare gen resource SecurityEvent`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=3e62bbc407b9
import { ResourceListSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return <ResourceListSkeleton columns={6} />;
}
// generated:end
