// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=74115432cab8
import { ResourceListSkeleton } from "@/components/dashboard/skeletons";

export default function Loading() {
  return <ResourceListSkeleton columns={5} />;
}
// generated:end
