// Generated by `flare gen resource Decision`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=71163af25efd
import { PageHeader } from "@/components/dashboard/page-header";
import { ResourceChart } from "@/components/dashboard/resource-chart";
import { ResourceStats } from "@/components/dashboard/resource-stats";
import { ResourceTable } from "@/components/dashboard/resource-table";
import type { SearchParams } from "@/components/dashboard/query";
import decisionResource from "@/resources/decision.resource";

export const metadata = { title: decisionResource.pluralLabel };

export default async function DecisionListPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  return (
    <>
      <PageHeader
        title={decisionResource.pluralLabel}
        crumbs={[{ label: "Dashboard", href: "/dashboard" }, { label: decisionResource.pluralLabel }]}
      />
      <ResourceStats resource={decisionResource} />
      <ResourceChart resource={decisionResource} />
      <ResourceTable resource={decisionResource} searchParams={await searchParams} />
    </>
  );
}
// generated:end
