// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=58b5f83d47ad
import { ResourceFormPage } from "@/components/dashboard/resource-form-page";
import componentResource from "@/resources/component.resource";

export default async function EditComponentPage({ params }: { params: Promise<{ id: string }> }) {
  return <ResourceFormPage resource={componentResource} id={(await params).id} />;
}
// generated:end
