// Generated by `flare gen resource Component`. Code inside the generated block is
// rewritten on regeneration; add your own code outside it.
// generated:start hash=77955edfb25b
import { createResourceStore, prismaRows, crossOrigin, drain, failureResponse, problem, readJson, respond } from "@/lib/resource";
import { prisma } from "@/lib/db";
import { authorize, currentUser, policyFor } from "@/lib/api";
import { revalidateResource } from "@/lib/cache";
import componentResource from "@/resources/component.resource";

const store = createResourceStore({
  resource: componentResource,
  rows: prismaRows(prisma.component, prisma),
  currentUser,
  // The role half of the policy is checked by authorize() below; the `own` half
  // restricts which rows exist for this user, which only the store can do.
  policy: policyFor("Component"),
  onChange: revalidateResource,
});

/** GET /api/components — list components. Query: page, perPage, sort, q, filter[field], cursor. */
export async function GET(request: Request): Promise<Response> {
  const denied = await authorize({ request, resource: componentResource, action: "list" });
  if (denied) return denied;

  return respond(await store.list(new URL(request.url).searchParams));
}

/** POST /api/components — create one. */
export async function POST(request: Request): Promise<Response> {
  try {
    const denied = await authorize({ request, resource: componentResource, action: "create" });
    if (denied) return denied;
    if (crossOrigin(request)) return problem(403, "Cross-origin request blocked.");

    const read = await readJson(request);
    if ("response" in read) return read.response;

    const result = await store.create(read.body);
    if (!result.ok) return failureResponse(result);

    const location = `${new URL(request.url).pathname.replace(/\/$/, "")}/${result.data.id as string}`;
    return Response.json(result.data, { status: 201, headers: { location } });
  } finally {
    // A body left unread breaks the next request through wrangler's dev proxy.
    await drain(request);
  }
}
// generated:end
